<?php

/**
 * Register Post Types.
*/
$labels = array(
	'name'                  => 'Новости',
	'singular_name'         => 'Новость',
	'menu_name'             => 'Новости',
	'name_admin_bar'        => 'Новости',
	'archives'              => 'Новости',
	'label'                 => 'Новости',
	'description'           => 'Новости',
	'attributes'            => 'Атрибуты новости',
	'parent_item_colon'     => 'Родительская новость:',
	'all_items'             => 'Все Новости',
	'add_new_item'          => 'Добавить новую новость',
	'add_new'               => 'Добавить новую',
	'new_item'              => 'Новая новость',
	'edit_item'             => 'Редактировать новость',
	'update_item'           => 'Обновить новость',
	'view_item'             => 'Посмотреть новость',
	'view_items'            => 'Посмотреть Новости',
	'search_items'          => 'Поиск новостей',
	'not_found'             => 'Не найдено',
	'not_found_in_trash'    => 'Не найдено в корзине',
	'featured_image'        => 'Изображение',
	'set_featured_image'    => 'Установить изображение',
	'remove_featured_image' => 'Удалить изображение',
	'use_featured_image'    => 'Использовать как изображение записи',
	'insert_into_item'      => 'Вставить в новость',
	'uploaded_to_this_item' => 'Загрузить в новость',
	'items_list'            => 'Список новостей',
	'items_list_navigation' => 'Навигация по новостям',
);
$args = array(
	'public'                => true,
	'labels'                => $labels,
	'show_ui'               => true,
	'show_in_menu'          => true,
	'show_in_nav_menus'     => false,
	'query_var'             => true,
	'rewrite'               => true,
	'capability_type'       => 'page',
	'has_archive'           => true,
	'hierarchical'          => false,
	'menu_position'         => 7,
	'supports'              => array( 'title', 'thumbnail' ),
	'menu_icon'             => 'dashicons-editor-kitchensink',
	'publicly_queryable'    => true,
	'show_in_admin_bar'     => true,
	'can_export'            => true,
	'taxonomies'            => array( 'section', 'categories', 'tags' ),
	'show_in_rest'          => true,
);
register_post_type( 'news', $args );

/**
 * Register taxonomies.
*/
register_taxonomy( 'section', ['news'], array(
		'label'                 => '',
		'labels'                => array(
				'name'              => 'Разделы',
				'singular_name'     => 'Раздел',
				'search_items'      => 'Поиск разделы',
				'all_items'         => 'Все разделы',
				'view_item '        => 'Просмотр разделы',
				'parent_item'       => 'Родительский раздел',
				'parent_item_colon' => 'Родительский раздел:',
				'edit_item'         => 'Изменить раздел',
				'update_item'       => 'Обновить раздел',
				'add_new_item'      => 'Добавить новый раздел',
				'new_item_name'     => 'Название новой разделы',
				'menu_name'         => 'Раздел',
		),
		'description'           => '',
		'public'                => true,
		'hierarchical'          => false,
		'rewrite'               => false,
		'query_var'             => 'section',
		'capabilities'          => array(),
		'meta_box_cb'           => 'post_categories_meta_box',
		'show_admin_column'     => true,
		'show_in_rest'          => true,
		'rest_base'             => null,
) );

register_taxonomy( 'categories', ['news'], array(
		'label'                 => '',
		'labels'                => array(
				'name'              => 'Категории',
				'singular_name'     => 'Категория',
				'search_items'      => 'Поиск категории',
				'all_items'         => 'Все категории',
				'view_item '        => 'Просмотр категории',
				'parent_item'       => 'Родительская категория',
				'parent_item_colon' => 'Родительская категория:',
				'edit_item'         => 'Изменить категория',
				'update_item'       => 'Обновить категорию',
				'add_new_item'      => 'Добавить новую категорию',
				'new_item_name'     => 'Название новой категории',
				'menu_name'         => 'Категория',
		),
		'description'           => '',
		'public'                => true,
		'hierarchical'          => false,
		'rewrite'               => false,
		'query_var'             => 'categories',
		'capabilities'          => array(),
		'meta_box_cb'           => 'post_categories_meta_box',
		'show_admin_column'     => true,
		'show_in_rest'          => true,
		'rest_base'             => null,
) );

register_taxonomy( 'tags', ['news'], array(
	'label'                 => '',
	'labels'                => array(
		'name'              => 'Метки',
		'singular_name'     => 'Метки',
		'search_items'      => 'Поиск меток',
		'all_items'         => 'Все метки',
		'view_item '        => 'Просмотр меток',
		'parent_item'       => 'Родительская метка',
		'parent_item_colon' => 'Родительская метка:',
		'edit_item'         => 'Изменить метку',
		'update_item'       => 'Обновить метку',
		'add_new_item'      => 'Добавить новую метку',
		'new_item_name'     => 'Название новой метки',
		'menu_name'         => 'Метки',
	),
	'description'           => '',
	'public'                => true,
	'hierarchical'          => false,
	'rewrite'               => false,
	'query_var'             => 'tags',
	'capabilities'          => array(),
	'meta_box_cb'           => 'post_categories_meta_box',
	'show_admin_column'     => true,
	'show_in_rest'          => true,
	'rest_base'             => null,
) );
